# name: CI/CD for NestJS with Vercel

# # env:
# #   VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
# #   VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Sao chép mã nguồn
#         uses: actions/checkout@v2

#       - name: Cài đặt môi trường Node.js
#         uses: actions/setup-node@v2
#         with:
#           node-version: 20.x

#       - name: Cài đặt phụ thuộc
#         run: npm install

#       - name: Xây dựng dự án
#         run: npm run build

#   # test:
#   #   runs-on: ubuntu-latest
#   #   needs: build
#   #   steps:
#   #     - name: Sao chép mã nguồn
#   #       uses: actions/checkout@v2

#   #     - name: Cài đặt môi trường Node.js
#   #       uses: actions/setup-node@v2
#   #       with:
#   #         node-version: 20.x

#   #     - name: Cài đặt phụ thuộc
#   #       run: npm install

#   #     - name: Kiểm thử đơn vị
#   #       run: npm run test

#   #     - name: Kiểm thử tích hợp
#   #       run: npm run test:e2e
# #   deploy:
# #     runs-on: ubuntu-latest
# #     needs: test

# #     steps:
# #       - name: Sao chép mã nguồn
# #         uses: actions/checkout@v2

# #       - name: Cài đặt Vercel CLI
# #         run: npm install --global vercel@latest

# #       - name: Vercel pull
# #         run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

# #       - name: Vercel build
# #         run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

# #       - name: Vercel deploy
# #         run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
